"""
SQL 导出器 — 将解析后的结构化日志生成 SQL INSERT 语句。

与项目一（log-audit-system）的数据库 schema 对应：
- 目标表: log_entry
- 字段: timestamp, ip_address, username, operation,
         operation_result, detail, severity, source_file

面试亮点：这个模块体现了跨项目的整体设计思维——
Python 解析工具产出的结构化数据可以直接导入 Java 后端的 MySQL 数据库。
"""

import logging
import os
from typing import Optional

import pandas as pd

logger = logging.getLogger(__name__)

# 项目一的 log_entry 表结构
INSERT_TEMPLATE = (
    "INSERT INTO log_entry "
    "(timestamp, ip_address, username, operation, operation_result, "
    "detail, severity, source_file) "
    "VALUES ({timestamp}, {ip_address}, {username}, {operation}, "
    "{operation_result}, {detail}, {severity}, {source_file});"
)


def _escape_sql(value: Optional[str]) -> str:
    """转义 SQL 字符串值。"""
    if value is None or pd.isna(value):
        return "NULL"
    escaped = str(value).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def _format_timestamp(value) -> str:
    """将时间戳格式化为 MySQL datetime 字符串。"""
    if value is None or pd.isna(value):
        return "NULL"
    try:
        ts = pd.Timestamp(value)
        return f"'{ts.strftime('%Y-%m-%d %H:%M:%S')}'"
    except (ValueError, TypeError):
        return _escape_sql(str(value))


def generate_insert_sql(df: pd.DataFrame) -> str:
    """
    将 DataFrame 转换为 SQL INSERT 语句。

    Args:
        df: 解析后的日志 DataFrame

    Returns:
        str: 完整的 SQL INSERT 语句（多条，分号分隔）
    """
    logger.info("Generating SQL INSERT statements for %d rows...", len(df))

    statements = ["-- Auto-generated by log-parser", "-- Target: log_entry table in log_audit database", ""]

    field_map = {
        "timestamp": ("timestamp", _format_timestamp),
        "ip_address": ("ip_address", _escape_sql),
        "username": ("username", _escape_sql),
        "operation": ("operation", _escape_sql),
        "operation_result": ("operation_result", _escape_sql),
        "detail": ("detail", _escape_sql),
        "severity": ("severity", _escape_sql),
        "source_file": ("source_file", _escape_sql),
    }

    for _, row in df.iterrows():
        values = {}
        for df_col, (sql_col, formatter) in field_map.items():
            if df_col in df.columns:
                values[sql_col] = formatter(row[df_col])
            else:
                values[sql_col] = "NULL"

        sql = (
            f"INSERT INTO log_entry "
            f"(timestamp, ip_address, username, operation, operation_result, "
            f"detail, severity, source_file) "
            f"VALUES ("
            f"{values['timestamp']}, "
            f"{values['ip_address']}, "
            f"{values['username']}, "
            f"{values['operation']}, "
            f"{values['operation_result']}, "
            f"{values['detail']}, "
            f"{values['severity']}, "
            f"{values['source_file']}"
            f");"
        )
        statements.append(sql)

    result = "\n".join(statements)
    logger.info("Generated %d INSERT statements.", len(df))
    return result


def export_to_sql_file(
    df: pd.DataFrame,
    output_path: str,
) -> str:
    """
    将 DataFrame 导出为 SQL 文件，可直接导入 MySQL。

    用法：
        mysql -u root -p log_audit < output/parsed_data.sql

    Args:
        df: 解析后的日志 DataFrame
        output_path: 输出 SQL 文件路径

    Returns:
        str: 输出文件的绝对路径
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    sql_content = generate_insert_sql(df)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(sql_content)

    logger.info("SQL file written: %s", output_path)
    return os.path.abspath(output_path)
